name: rize-scheduler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - httpx>=0.24.0
  - pydantic>=2.0.0
  - python-dotenv>=1.0.0
  - colorama>=0.4.6
  - pip:
    - mcp>=1.0.0
    - graphql-core>=3.2.0